-- Tabela de Metas (Goals)
create table public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  title text not null,
  description text,
  deadline date,
  is_completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabela de View Groups (Grupos de Visualização)
create table public.view_groups (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  title text not null,
  start_time time,
  end_time time,
  type text,
  icon text,
  color text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabela de Afazeres (Todos)
create table public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  title text not null,
  is_completed boolean default false,
  goal_id bigint references public.goals(id) on delete set null, -- Pode estar atrelado a uma meta ou não
  view_group_id bigint references public.view_groups(id) on delete set null, -- Grupo de visualização
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabela de Eventos (Events)
create table public.events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  title text not null,
  description text,
  start_date timestamp with time zone not null,
  end_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS (Row Level Security) para segurança
alter table public.goals enable row level security;
alter table public.todos enable row level security;
alter table public.events enable row level security;
alter table public.view_groups enable row level security;

-- Políticas de Segurança (Cada usuário só vê e edita seus próprios dados)

-- GOALS
create policy "Users can view their own goals" on public.goals
  for select using (auth.uid() = user_id);

create policy "Users can insert their own goals" on public.goals
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own goals" on public.goals
  for update using (auth.uid() = user_id);

create policy "Users can delete their own goals" on public.goals
  for delete using (auth.uid() = user_id);

-- VIEW GROUPS
create policy "Users can view their own view_groups" on public.view_groups
  for select using (auth.uid() = user_id);

create policy "Users can insert their own view_groups" on public.view_groups
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own view_groups" on public.view_groups
  for update using (auth.uid() = user_id);

create policy "Users can delete their own view_groups" on public.view_groups
  for delete using (auth.uid() = user_id);

-- TODOS
create policy "Users can view their own todos" on public.todos
  for select using (auth.uid() = user_id);

create policy "Users can insert their own todos" on public.todos
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own todos" on public.todos
  for update using (auth.uid() = user_id);

create policy "Users can delete their own todos" on public.todos
  for delete using (auth.uid() = user_id);

-- EVENTS
create policy "Users can view their own events" on public.events
  for select using (auth.uid() = user_id);

create policy "Users can insert their own events" on public.events
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own events" on public.events
  for update using (auth.uid() = user_id);

create policy "Users can delete their own events" on public.events
  for delete using (auth.uid() = user_id);
