-- Tabela de Transações Financeiras (Finance Transactions)
create table public.finance_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  title text not null,
  amount numeric(10, 2) not null,
  transaction_date date not null,
  type text not null check (type in ('payable', 'receivable')),
  status text not null default 'pending' check (status in ('pending', 'paid', 'overdue')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.finance_transactions enable row level security;

-- Políticas de Segurança
create policy "Users can view their own transactions" on public.finance_transactions
  for select using (auth.uid() = user_id);

create policy "Users can insert their own transactions" on public.finance_transactions
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own transactions" on public.finance_transactions
  for update using (auth.uid() = user_id);

create policy "Users can delete their own transactions" on public.finance_transactions
  for delete using (auth.uid() = user_id);
