-- Tabela de Projetos
create table public.projects (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text not null,
  color text default '#6366f1',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.projects enable row level security;

-- Políticas de Segurança
create policy "Users can view their own projects" on public.projects
  for select using (auth.uid() = user_id);

create policy "Users can insert their own projects" on public.projects
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own projects" on public.projects
  for update using (auth.uid() = user_id);

create policy "Users can delete their own projects" on public.projects
  for delete using (auth.uid() = user_id);

-- Adicionar project_id na tabela todos
alter table public.todos add column if not exists project_id bigint references public.projects(id) on delete set null;

-- Adicionar project_id na view_groups para vinculação opcional
alter table public.view_groups add column if not exists project_id bigint references public.projects(id) on delete set null;
