-- Tabela N:N para membros de projetos
create table public.project_members (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(project_id, user_id)
);

-- Habilitar RLS
alter table public.project_members enable row level security;

-- Políticas: membros veem projetos; só dono pode gerenciar membros
create policy "Users can view project members of their projects" on public.project_members
  for select using (
    auth.uid() = user_id or
    exists (
      select 1 from public.projects
      where id = project_id and owner_id = auth.uid()
    )
  );

create policy "Project owners can manage members" on public.project_members
  for all using (
    exists (
      select 1 from public.projects
      where id = project_id and owner_id = auth.uid()
    )
  );

-- Ajustar RLS da tabela projects para usar owner_id
drop policy if exists "Users can view their own projects" on public.projects;
drop policy if exists "Users can view their own projects or shared" on public.projects;
create policy "Users can view projects they own or are members of" on public.projects
  for select using (
    auth.uid() = owner_id or
    exists (select 1 from public.project_members pm where pm.project_id = id and pm.user_id = auth.uid())
  );

drop policy if exists "Users can update their own projects" on public.projects;
drop policy if exists "Users can update their own projects or shared" on public.projects;
create policy "Project owners can update" on public.projects
  for update using (auth.uid() = owner_id);

drop policy if exists "Users can insert their own projects" on public.projects;
create policy "Users can insert projects" on public.projects
  for insert with check (auth.uid() = owner_id);

drop policy if exists "Users can delete their own projects" on public.projects;
create policy "Project owners can delete" on public.projects
  for delete using (auth.uid() = owner_id);
