-- Tabela de Seções (dentro de projetos)
create table public.sections (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  project_id bigint references public.projects(id) on delete cascade not null,
  title text not null,
  "order" integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.sections enable row level security;

-- Políticas de Segurança
create policy "Users can view their own sections" on public.sections
  for select using (auth.uid() = user_id);

create policy "Users can insert their own sections" on public.sections
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own sections" on public.sections
  for update using (auth.uid() = user_id);

create policy "Users can delete their own sections" on public.sections
  for delete using (auth.uid() = user_id);

-- Adicionar section_id na tabela todos
alter table public.todos add column if not exists section_id bigint references public.sections(id) on delete set null;
