-- Tabela de convites de projetos
create table public.project_invites (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id) on delete cascade not null,
  invited_user_id uuid references auth.users(id) on delete cascade not null,
  invited_by_user_id uuid references auth.users(id) on delete cascade not null,
  status text default 'pending' check (status in ('pending', 'accepted', 'declined')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(project_id, invited_user_id)
);

-- Habilitar RLS
alter table public.project_invites enable row level security;

-- Políticas RLS para convites
-- Usuários podem ver convites destinados a eles
create policy "Users can view their invites" on public.project_invites
  for select using (auth.uid() = invited_user_id);

-- Donos de projetos podem ver convites dos seus projetos
create policy "Project owners can view invites" on public.project_invites
  for select using (
    exists (select 1 from public.projects where id = project_id and owner_id = auth.uid())
  );

-- Qualquer pessoa pode criar convite (será validado no app)
create policy "Anyone can create invites" on public.project_invites
  for insert with check (
    exists (select 1 from public.projects where id = project_id and owner_id = auth.uid())
  );

-- Apenas o convidado pode atualizar (aceitar/recusar)
create policy "Invited users can update their invites" on public.project_invites
  for update using (auth.uid() = invited_user_id);

-- Donos podem deletar convites
create policy "Project owners can delete invites" on public.project_invites
  for delete using (
    exists (select 1 from public.projects where id = project_id and owner_id = auth.uid())
  );
