-- Compartilhamento granular: pasta (section) inteira ou apenas uma tarefa,
-- sem precisar tornar o usuário membro do projeto inteiro.
--
-- Regra de visibilidade em cascata: quem recebe acesso a uma tarefa também
-- enxerga a pasta e o projeto que a contêm (como containers, possivelmente
-- vazios de outras tarefas) — a query de tasks continua filtrando pelo RLS
-- normalmente, então só aparecem as tarefas às quais o usuário realmente tem acesso.

-- 1. Tabelas de compartilhamento
create table public.section_shares (
  id bigint generated by default as identity primary key,
  section_id bigint references public.sections(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(section_id, user_id)
);

create table public.task_shares (
  id bigint generated by default as identity primary key,
  task_id bigint references public.todos(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(task_id, user_id)
);

alter table public.section_shares enable row level security;
alter table public.task_shares enable row level security;

create index if not exists idx_section_shares_user on public.section_shares(user_id);
create index if not exists idx_task_shares_user on public.task_shares(user_id);

-- 2. "Dono automático" da pasta: tarefas criadas nela já nascem direcionadas a esse usuário
alter table public.sections add column if not exists default_assignee_id uuid references auth.users(id) on delete set null;

-- 2b. Responsável da tarefa (separado do criador em user_id)
alter table public.todos add column if not exists assignee_id uuid references auth.users(id) on delete set null;
create index if not exists idx_todos_assignee on public.todos(assignee_id);

-- 3. Funções helper (security definer para não recursar em RLS)
create or replace function public.is_section_shared(p_section_id bigint, p_user_id uuid)
returns boolean as $$
  select exists (
    select 1 from public.section_shares where section_id = p_section_id and user_id = p_user_id
  );
$$ language sql stable security definer;

create or replace function public.is_task_shared(p_task_id bigint, p_user_id uuid)
returns boolean as $$
  select exists (
    select 1 from public.task_shares where task_id = p_task_id and user_id = p_user_id
  );
$$ language sql stable security definer;

-- Alguém enxerga a pasta se: é dono/membro do projeto, a pasta foi compartilhada
-- diretamente, ou pelo menos uma tarefa dela foi compartilhada com ele.
create or replace function public.has_section_access(p_section_id bigint, p_user_id uuid)
returns boolean as $$
  select
    exists (
      select 1 from public.sections s
      where s.id = p_section_id
        and (s.user_id = p_user_id or public.is_project_member(s.project_id, p_user_id))
    )
    or public.is_section_shared(p_section_id, p_user_id)
    or exists (
      select 1 from public.todos t
      where t.section_id = p_section_id and public.is_task_shared(t.id, p_user_id)
    );
$$ language sql stable security definer;

-- Alguém enxerga o projeto se: é dono/membro, ou tem acesso a alguma pasta/tarefa dele.
create or replace function public.has_project_access(p_project_id bigint, p_user_id uuid)
returns boolean as $$
  select
    public.is_project_member(p_project_id, p_user_id)
    or exists (
      select 1 from public.sections s
      where s.project_id = p_project_id and public.is_section_shared(s.id, p_user_id)
    )
    or exists (
      select 1 from public.todos t
      where t.project_id = p_project_id and public.is_task_shared(t.id, p_user_id)
    );
$$ language sql stable security definer;

-- 4. projects: visível também via compartilhamento de pasta/tarefa
drop policy if exists "projects_select_owner_or_member" on public.projects;
create policy "projects_select_owner_or_member" on public.projects
  for select using (
    auth.uid() = owner_id
    or public.has_project_access(id, auth.uid())
  );

-- 5. sections: visível também via compartilhamento direto ou de tarefa interna
drop policy if exists "Project members can view sections" on public.sections;
create policy "Project members can view sections" on public.sections
  for select using (
    public.has_section_access(id, auth.uid())
  );

-- 6. todos: visível/editável também via compartilhamento de pasta ou da própria tarefa
drop policy if exists "Project members can view tasks" on public.todos;
create policy "Project members can view tasks" on public.todos
  for select using (
    auth.uid() = user_id
    or assignee_id = auth.uid()
    or (project_id is not null and public.is_project_member(project_id, auth.uid()))
    or (section_id is not null and public.is_section_shared(section_id, auth.uid()))
    or public.is_task_shared(id, auth.uid())
  );

drop policy if exists "Project members can insert tasks" on public.todos;
create policy "Project members can insert tasks" on public.todos
  for insert with check (
    auth.uid() = user_id
    or (project_id is not null and public.is_project_member(project_id, auth.uid()))
    or (section_id is not null and public.is_section_shared(section_id, auth.uid()))
  );

drop policy if exists "Project members can update tasks" on public.todos;
create policy "Project members can update tasks" on public.todos
  for update using (
    auth.uid() = user_id
    or assignee_id = auth.uid()
    or (project_id is not null and public.is_project_member(project_id, auth.uid()))
    or (section_id is not null and public.is_section_shared(section_id, auth.uid()))
    or public.is_task_shared(id, auth.uid())
  );

-- DELETE continua restrito ao criador ou a membros do projeto:
-- acesso via pasta/tarefa compartilhada não permite excluir.
drop policy if exists "Project members can delete tasks" on public.todos;
create policy "Project members can delete tasks" on public.todos
  for delete using (
    auth.uid() = user_id
    or (project_id is not null and public.is_project_member(project_id, auth.uid()))
  );

-- 7. Quem pode compartilhar: dono da pasta/tarefa ou membro do projeto dela.
-- O próprio usuário que recebeu acesso também pode remover a si mesmo (deixar de ver).
create policy "Section owners manage section shares" on public.section_shares
  for all using (
    user_id = auth.uid()
    or exists (
      select 1 from public.sections s
      where s.id = section_id and (s.user_id = auth.uid() or public.is_project_member(s.project_id, auth.uid()))
    )
  )
  with check (
    exists (
      select 1 from public.sections s
      where s.id = section_id and (s.user_id = auth.uid() or public.is_project_member(s.project_id, auth.uid()))
    )
  );

create policy "Task owners manage task shares" on public.task_shares
  for all using (
    user_id = auth.uid()
    or exists (
      select 1 from public.todos t
      where t.id = task_id
        and (t.user_id = auth.uid() or (t.project_id is not null and public.is_project_member(t.project_id, auth.uid())))
    )
  )
  with check (
    exists (
      select 1 from public.todos t
      where t.id = task_id
        and (t.user_id = auth.uid() or (t.project_id is not null and public.is_project_member(t.project_id, auth.uid())))
    )
  );

-- 8. Pasta com "dono automático": nova tarefa já nasce direcionada a ele
create or replace function public.apply_section_default_assignee()
returns trigger as $$
begin
  if new.assignee_id is null and new.section_id is not null then
    select default_assignee_id into new.assignee_id
    from public.sections where id = new.section_id;
  end if;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists trg_apply_section_default_assignee on public.todos;
create trigger trg_apply_section_default_assignee
  before insert on public.todos
  for each row execute function public.apply_section_default_assignee();
